version: '2'
services:
  proxy:
    image: jwilder/nginx-proxy
    container_name: foro-nginx-proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - "80:80"

  foro:
    build: ./categorias
    image: foro/categorias
    container_name: foro-categorias
    depends_on:
      - db
      - proxy
    links:
      - db
    environment:
      VIRTUAL_HOST: foro.local

  db:
    image: mongo:3.3
    container_name: foro-db
    ports:
      - "27017:27017"
    volumes:
      - ./backup:/backup:rw